services:
  debian-simulator_automatic_warehouse:
    build:
      context: ../.
      dockerfile: docker/Dockerfile-debian
    environment:
      WAREHOUSE_CONFIGURATION_FILE_PATH: configuration/sample_config.yaml
  alpine-simulator_automatic_warehouse:
    build:
      context: ../.
      dockerfile: docker/Dockerfile-alpine
    environment:
      WAREHOUSE_CONFIGURATION_FILE_PATH: configuration/sample_config.yaml