FROM python:3.12.4-alpine
LABEL authors="AndreVale69"

RUN mkdir /simulator-automatic-warehouse
WORKDIR /simulator-automatic-warehouse

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip -r requirements.txt
COPY src/ src
COPY run_simulator.py run_simulator.py
COPY configuration/ configuration
COPY resources/configuration/json_schema.json resources/configuration/json_schema.json

CMD ["python", "run_simulator.py"]