version: "3.8"
services:
  simulator_automatic_warehouse:
    build:
      context: ../.
      dockerfile: Dockerfile
    environment:
      WAREHOUSE_CONFIGURATION_FILE_PATH: configuration/univr/ICE_lab.yaml
      HOST: 127.0.0.1
      PORT: 8050
    network_mode: host