FROM python:3.12.4-slim
LABEL authors="AndreVale69"

RUN mkdir /simulator-automatic-warehouse
WORKDIR /simulator-automatic-warehouse

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip -r requirements.txt
COPY automatic_warehouse/ automatic_warehouse
COPY run_simulator.py run_simulator.py
COPY automatic_warehouse-config/ automatic_warehouse-config
COPY automatic_warehouse-res/configuration/json_schema.json automatic_warehouse-res/configuration/json_schema.json

CMD ["python", "run_simulator.py"]